### ISSUE TITLE
Setting 👁️🫦👁️ as a key in kvp results in 500 from controller

### ISSUE THREAD

**Issue by snickell** [code-dot-org/code-dot-org#56761]
ActiveRecord::StatementInvalid in DatablockStorageController#set_key_value

Mysql2::Error: Incorrect string value: '\xF0\x9F\x91\x81\xEF\xB8...' for column 'key' at row 1

Extracted source (around line #151):

#149     def query(sql, options = {})
#150       Thread.handle_interrupt(::Mysql2::Util::TIMEOUT_ERROR_NEVER) do
*151         _query(sql, @query_options.merge(options))
#152       end
#153     end
#154 

Extracted source (around line #150):

#148 
#149     def query(sql, options = {})
*150       Thread.handle_interrupt(::Mysql2::Util::TIMEOUT_ERROR_NEVER) do
#151         _query(sql, @query_options.merge(options))
#152       end
#153     end

Rails.root: /home/ubuntu/adhoc/dashboard

Application Trace
config/initializers/mysql_check_index_used.rb:33:in `block (3 levels) in execute'
config/initializers/mysql_check_index_used.rb:32:in `block (2 levels) in execute'
config/initializers/mysql_check_index_used.rb:31:in `block in execute'
config/initializers/mysql_check_index_used.rb:30:in `execute'
app/models/datablock_storage_kvp.rb:23:in `set_kvps'
app/models/datablock_storage_kvp.rb:31:in `set_kvp'
app/controllers/datablock_storage_controller.rb:26:in `set_key_value'
app/controllers/application_controller.rb:186:in `block in with_locale'
app/controllers/application_controller.rb:185:in `with_locale'

**Comment by snickell** [comment]
Fixed by [#56837](https://github.com/code-dot-org/code-dot-org/pull/56837)
